export const APPEND_OPERATION = 'APPEND_OPERATION';
export const UPDATE_OPERATION = 'UPDATE_OPERATION';
export const DELETE_OPERATION = 'DELETE_OPERATION';
export const MOVE_UP_OPERATION = 'MOVE_UP_OPERATION';
export const MOVE_DOWN_OPERATION = 'MOVE_DOWN_OPERATION';
export const CLEAR_OPERATIONS = 'CLEAR_OPERATIONS';
export const APPEND_RESULT = 'APPEND_RESULT';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';